version: '3.8'

services:
  frontend:
    build:
      context: client
      target: prod
    ports:
      - '5173:5173'
    volumes:
      - ./client:/project
      - /project/node_modules

  deployment:
    build:
      context: client
      target: deploy
    ports:
      - "80:80"
    depends_on:
      - frontend

  server:
    build:
      context: server
      target: dev
    ports:
      - '8000:8000'
    volumes:
      - ./server:/backend
