version: '3.8'

services:
  frontend:
    build:
      context: client
      target: dev
    ports:
      - '5173:5173'
    volumes:
      - ./client:/project
      - /project/node_modules

  server:
    build:
      context: server
      target: dev
    ports:
      - '8000:8000'
    volumes:
      - ./server:/backend