version: '3.8'

services:
  frontend:
    build:
      context: client
      target: prod
    ports:
      - '5173:5173'
    volumes:
      - ./client:/project
      - /project/node_modules

  server:
    build:
      context: server
      target: dev
    ports:
      - '8000:8000'
    volumes:
      - ./server:/backend

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./client/dist:/var/www/html:cached
    restart: always
    depends_on:
      - frontend